### ISSUE TITLE
CLI not switching to API logs when needed

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#238]
### Description:

Whenever I run the product in dev mode, I am not able to switch logs between web server and api server.

### Steps to reproduce:

1.  `./dev.sh`
2.  switch between server logs. and switch to api-server logs. `[w]`

### Expected behaviour:

- It should switch logs to API server.

### Actual behavior:

- Cant switch between logs.
![image](https://github.com/middlewarehq/middleware/assets/70485812/b95ef168-d9d6-4e5c-9e59-7e89d9e7283b)

### Server Setup Information:

- Operating System: Mac OS 14
- Deployment Method:

**Comment by Kamlesh72** [comment]
The bug is there due to the way \<Static\> element prints the logsStreamNodes to the CLI.
Let's say the current log source is "web" and logsStream has 10 logs.
Now if we press key to switch to log source "API" which let's say has 18 logs.
Then \<Static\> element will only show ( 18 - 10 = 8 logs ).
Now if we again switch to log source "web" which has 10 logs, the element will not show any logs.
That means \<Static\> element only extra logs that are added to logStream, which is expected.

One way to solve the problem is to dispatch logStream = [ ] on any input.
![Screenshot 2024-07-10 at 11 43 21 AM](https://github.com/middlewarehq/middleware/assets/90441742/37d08aed-6f12-46cc-a9ca-874871ed6b7c)

However, If same log source is selected again, it will compute the conversion of logStream logs to nodes again (which we can handle by logic or just ignore). Also fortunately the same log source logs will not be printed again on CLI.
We can discuss more if this approach seems fine. I will be happy to create a PR for this.

**Comment by shivam-bit** [comment]
`Then the <Static> element will only show (18 - 10 = 8 logs).`
@Kamlesh72, thanks for this^
Maybe now we know why the `<Static>` element was giving us issues.

One of the behaviors that we expect from our CLI logs is that when we switch between sources, it should also print the last 50 logs from that source. If I am guessing it right, your approach will totally clear it out.
But even if it does so, please raise a PR with your existing approach, as it will fix the switching of log source issue.

**Comment by Kamlesh72** [comment]
@shivam-bit On any input, we are dispatching payload 2 times. 1st with [ ] and 2nd with respective logs array. Hence CLI will work as it it.


https://github.com/middlewarehq/middleware/assets/90441742/dadb2fcb-715b-4c59-a14e-6a8336d47cce
