### ISSUE TITLE
Lead Time information missing

### ISSUE THREAD

**Issue by mewid** [middlewarehq/middleware#364]
### Description:

![image](https://github.com/middlewarehq/middleware/assets/93190006/ce2f8949-d2f6-44c3-a8ed-4e294d59998d)

### Expected behavior:

No missing lead time information

### Actual behavior:

Lead Time information missing

### Server Setup Information:

Running Docker image with tag ":latest", downloaded 15 of May 2024

### Additional context

When querying the Github events API, I get the following events related to the PR or branch in question:

```
{
  "type": "PullRequestEvent",
  "payload": {
    "action": "closed",
    "number": 1420,
    "pull_request": {
      "number": 1420,
      "state": "closed",
      "created_at": "2024-05-10T14:21:39Z",
      "updated_at": "2024-05-13T13:18:54Z",
      "closed_at": "2024-05-13T13:18:54Z",
      "merged_at": "2024-05-13T13:18:54Z",
      "head": {
        "repo": {
          "created_at": "2022-03-08T14:38:43Z",
          "updated_at": "2024-05-13T12:27:28Z",
          "pushed_at": "2024-05-13T12:50:24Z",
          "default_branch": "main"
        }
      },
      "comments": 3,
      "review_comments": 0,
    }
  },
  "created_at": "2024-05-13T13:18:55Z"
},
{
  "type": "IssueCommentEvent",
  "payload": {
    "action": "created",
    "issue": {
      "state": "open",
      "comments": 3,
      "created_at": "2024-05-10T14:21:39Z",
      "updated_at": "2024-05-13T12:06:02Z",
    },
    "comment": {
      "created_at": "2024-05-13T12:06:00Z",
      "updated_at": "2024-05-13T12:06:00Z"
    }
  },
  "created_at": "2024-05-13T12:06:02Z",
},
{
  "type": "IssueCommentEvent",
  "payload": {
    "action": "created",
    "issue": {
      "state": "open",
      "comments": 2,
      "created_at": "2024-05-10T14:21:39Z",
      "updated_at": "2024-05-13T10:00:36Z",
      "closed_at": null
    },
    "comment": {
      "created_at": "2024-05-13T10:00:35Z",
      "updated_at": "2024-05-13T10:00:35Z",
    }
  },
  "created_at": "2024-05-13T10:00:36Z",
},
{
  "type": "IssueCommentEvent",
  "payload": {
    "action": "created",
    "issue": {
      "state": "open",
      "comments": 1,
      "created_at": "2024-05-10T14:21:39Z",
      "updated_at": "2024-05-13T09:44:38Z",
      "closed_at": null,
    },
    "comment": {
      "created_at": "2024-05-13T09:44:37Z",
      "updated_at": "2024-05-13T09:44:37Z"
    }
  },
  "created_at": "2024-05-13T09:44:38Z",
},
{
  "id": "38269240951",
  "type": "PullRequestEvent",
  "payload": {
    "action": "opened",
    "number": 1420,
    "pull_request": {
      "number": 1420,
      "state": "open",
      "created_at": "2024-05-10T14:21:39Z",
      "updated_at": "2024-05-10T14:21:39Z",
      "closed_at": null,
      "merged_at": null,
      "head": {
        "repo": {
          "created_at": "2022-03-08T14:38:43Z",
          "updated_at": "2024-05-10T08:20:11Z",
          "pushed_at": "2024-05-10T14:21:40Z",
          "default_branch": "main"
        }
      },
      "base": {
        "repo": {
          "created_at": "2022-03-08T14:38:43Z",
          "updated_at": "2024-05-10T08:20:11Z",
          "pushed_at": "2024-05-10T14:21:40Z",
        }
      }
    }
  },
  "public": false,
  "created_at": "2024-05-10T14:21:41Z"
},
{
  "type": "PushEvent",
  "payload": {
    "commits": [
      {
        "message": "1"
      }
    ]
  },
  "public": false,
  "created_at": "2024-05-10T14:38:54Z"
},
{
  "id": "38269212784",
  "type": "CreateEvent",
  "payload": {
    "ref_type": "branch",
    "master_branch": "main"
  },
  "created_at": "2024-05-10T14:20:51Z"
}
```
I was expecting to see the 4 first commits among the events as well, but that is not the case. Likely what happened is that the first 4 commits was created on the first branch push (which I assume is the "CreateEvent"). But I see no mention of those commits in the event itself.

When querying the PR with the GitHub API, I get the following information:

```
{
  "number": 1420,
  "state": "closed",
  "created_at": "2024-05-10T14:21:39Z",
  "updated_at": "2024-05-13T13:18:55Z",
  "closed_at": "2024-05-13T13:18:54Z",
  "merged_at": "2024-05-13T13:18:54Z",
  "head": {
    "repo": {
      "created_at": "2022-03-08T14:38:43Z",
      "updated_at": "2024-05-17T07:07:40Z",
      "pushed_at": "2024-05-17T12:16:31Z",
      "visibility": "internal"
    }
  },
  "base": {
    "ref": "main",
    "repo": {
      "created_at": "2022-03-08T14:38:43Z",
      "updated_at": "2024-05-17T07:07:40Z",
      "pushed_at": "2024-05-17T12:16:31Z"
    }
  }
}
```

Querying all the commits for the PR, I get this information:

```
[
  {
    "commit": {
      "author": {
        "date": "2024-05-10T12:45:22Z"
      },
      "committer": {
        "date": "2024-05-10T12:45:22Z"
      },
      "message": "1"
    }
  },
  {
    "commit": {
      "author": {
        "date": "2024-05-10T12:46:06Z"
      },
      "committer": {
        "date": "2024-05-10T12:46:06Z"
      },
      "message": "2"
    }
  },
  {
    "commit": {
      "author": {
        "date": "2024-05-10T12:48:50Z"
      },
      "committer": {
        "date": "2024-05-10T12:48:50Z"
      },
      "message": "3"
    }
  },
  {
    "commit": {
      "author": {
        "date": "2024-05-10T14:20:14Z"
      },
      "committer": {
        "date": "2024-05-10T14:20:14Z"
      },
      "message": "4"
    }
  },
  {
    "commit": {
      "author": {
        "date": "2024-05-10T14:38:50Z"
      },
      "committer": {
        "date": "2024-05-10T14:38:50Z"
      },
      "message": "5"

    }
  }
]
```

I have removed as much data as I could from the JSON bodies. I hope I left enough.

**Comment by samad-yar-khan** [comment]
Thanks for reporting this @mewid we will look into this issue and try to replicate it. Will get back to you on this soon.

**Comment by shivam-bit** [comment]
Hi @mewid,

Could you please answer the following two questions?

1. Has the PR received any review comments?
2. Has the PR been approved for merging?

Thank you.

**Comment by mewid** [comment]
Hello,

1. Yes. I would think those are the events with type: IssueCommentEvent
2. No actually, seems like there was no approval. It was merged directly.

**Comment by amoghjalan** [comment]
Hi @mewid !!
Thanks for the info and questions!

To get review info on GitHub, we use this API: `/repos/{owner}/{repo}/pulls/{pull_number}/reviews`. This way, only review events are counted, not regular comments.

Here's what the API docs [GitHub API Docs](https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28) tell us:
* IssueCommentEvent is for normal comments on issues.
* We use PullRequestReviewEvent for review events on pull requests.

Now, let's look at your pull request data and the calculated times.

### Lead Time Breakdown
**First Commit to PR Open:**
Time between first code commit and opening the pull request
* First Commit at: `2024-05-10T12:45:22Z`
* Pull Request Opened at: `2024-05-10T14:21:39Z`
* Time Difference: 1 hour 36 minutes 17 seconds
First Commit to PR Open: 1 hour 

**PR Open to First Response**
* Pull Request Opened at: `2024-05-10T14:21:39Z`
* Now, the Response could be either the PullRequestReviewEvent or the Approval Event because none were found hence
First Response Time = NULL

**Rework Time**
* Rework Time is calculated as time from first response (first PullRequestReviewEvent) to Approval Event if there is any commit found in between them. 
* Again because there is no PullRequestReviewEvent and approval event hence
Rework Time = NULL

**Merge Time**
* Calculated as time from Approval event to Merge Time as no Approval event
Merge Time = NULL

**Deploy Time**
* Calculated as Merge to deploy time, as currently we assume Merge = Deploy hence 
Deploy Time = 0

### Two Ways to Look at Lead Time
There are two ways to define lead time:
1. Detailed Breakdown: Add up all the times above (currently most are NULL).
2. Total Time: This is the simpler way we use now. It's the difference between the first commit time and the time the pull request was merged.

### Your Data's Lead Time
First Commit at: `2024-05-10T12:45:22Z`
PR Merged At: `2024-05-13T13:18:54Z`
Hence, Lead time = 3 days 0 hours 33 minutes 32 seconds
Shown as 3 hours after concatenation

I hope this clears the reason of data being there how it is.
Our current method gives a simple overall lead time. Let me know if you'd like to track the breakdowns (like merge time) even if they're NULL now. Maybe by changing how these are calculated today. Do you have any suggestion on how these definitions could be changed? We can see if the product can be updated to support that.

**Comment by mewid** [comment]
Right, that makes sense. Then I know that I can trust the aggregated value, which is the most important thing for now. If I come up with any suggestions for another behaviour, I can add it as an idea in the discussion-tab :)
